version: "3.8"
services:
  kafka-connect:
    build: .
    ports:
      - "8083:8083"
      - "7073:7073"
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-dev}
      KAFKA_CONNECT_LOG4J_ROOT_LOGLEVEL: ${KAFKA_CONNECT_LOG4J_ROOT_LOGLEVEL:-DEBUG}
      BROKERS: ${BROKERS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
