name: Deploy Kafka Connectors for AWS Datagen
on:
  push:
    paths:
      - 'connector-configs/kafka-connect-server-1/**'
  pull_request:
    paths:
      - 'connector-configs/kafka-connect-server-1/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: jaycobjones/kafka-connect-aws-datagen-on-prem-mqtt
      CONFIG_PATH: ./connector-configs/kafka-connect-server-1     
      VERSION: ${{ github.sha }}                        

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          # Use environment variables for image name, version, and config path
          docker build \
              -t $IMAGE_NAME:latest \
              -t $IMAGE_NAME:$VERSION $CONFIG_PATH

          # Push both latest and versioned tags to Docker Hub
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
